# Generated by Django 4.1.3 on 2023-01-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_sessionyearmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionYearModel',
        ),
    ]
