# Generated by Django 4.1.3 on 2023-01-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_sessionyearmodel_remove_student_session_end_year_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sessionyearmodel',
            managers=[
            ],
        ),
    ]
