# Generated by Django 4.1.3 on 2023-02-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_staff_fcm_token_student_fcm_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
