# Generated by Django 4.1.3 on 2023-02-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
    ]
