# Generated by Django 4.1.3 on 2023-02-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_studentresult_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
